### ISSUE TITLE
Al acceder a Datos me dá error 500

### ISSUE THREAD

**Issue by mvasquez74** [datosgobar/datos.gob.ar#10]
Antes que nada felicitar al equipo por excelente trabajo y documentación.

Instale CKAN siguiendo la documentación y funciona bien, instale los plugins que proponen y hasta el theme de gobAR, pero cuando intento acceder a la opcion de de DATOS me dá error 500. En la consola de dá el error que adjunto como imagen.

![errorckan](https://cloud.githubusercontent.com/assets/8423631/15935091/7e4512a0-2e3c-11e6-98fc-4c9c99bfc34b.png)

Cualquier ayuda será bienvenida
Marcelo

**Comment by vmartemianov** [comment]
Hola Marcelo,

Pueden ser muchas cosas distintas que generen errores de ese tipo. Yo primero chequearía la integridad del development.ini y me aseguraría de que los path sean los correctos, dado que al ser parecidos pueden generar confusión. En todo caso nos podrías pasar la configuración que estás aplicando?

**Comment by mvasquez74** [comment]
Hola Vladimir.

Yo seguí la siguiente documentación:
https://github.com/gobabiertoAR/datos.gob.ar/blob/master/docs/01_instalacion_dev.md

Hasta corri los test y todo funcionó OK. El Portal levanta y puedo navegar a Organizaciones, ver y descargar los dataset que cargue previamente y si comento el plugin del theme de gobiernoAR funciona bien CKAN.

Tal vel el theme o algunos de los plugin que usa el theme de gobiernoAR necesita alguna estructura minima de datos en la base y yo no la tengo.

De todas maneras te adjunto el development.ini y paralelamente estoy instalando CKAN en otra VM limpia para descartar que algo que haya instalado previamente este perjudicando. En cuanto tenga novedades lo comento.

[development.zip](https://github.com/gobabiertoAR/datos.gob.ar/files/312790/development.zip)

**Comment by vmartemianov** [comment]
Marcelo como estás

Configuré un servidor desde cero siguiendo el README y no tuve inconvenientes, me podrías pasar un correo tuyo para enviarte las credenciales del entorno de prueba funcionando? Tal vez te sirva ver un entorno andando para ver las diferencias. Caso contrario avisame y lo vemos puntualmente

Saludos!
