### ISSUE TITLE
Agregar sección APIs

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/datos.gob.ar#103]
Agregar la sección APIs que desarrolló Seba en datos.gob.ar

https://github.com/datosgobar/datosgobar-landing-apis/

**Comment by iheredia** [comment]
Desconozco si la descripción de la sección ya está cerrado, pero si van a linkear a la documentación de la api de ckan entonces no pongan `"Estos son servicios web desarrollados por el Ministerio de Modernización..."`. Da a entender que el ministerio es el autor de la api de ckan

**Comment by abenassi** [comment]
Mmm buen punto

**Comment by abenassi** [comment]
@chdigiorno 

El texto original 

"Estos son servicios web desarrollados por el Ministerio de Modernización sobre la base de datos públicos de organismos de gobierno de la República Argentina."

cambiémoslo por

"Estos son servicios web de datos públicos disponibilizados por organismos de gobierno de la República Argentina."

**Comment by poligarcia** [comment]
Traigo este comentario desde datosgobar/portal_datos.gob.ar#20:

Agregar una sección nueva en el portal datos.gob.ar con el contenido estático replicado de https://datosgobar.github.io/datosgobar-landing-apis/

El desagregado de requerimientos para dar por finalizado este issue es:

1. [x] Agregar el punto de menú APIs en el cabezal de datos.gob.ar
1. [x] Que exista una ruta `/apis` en el portal datos.gob.ar
1. [x] Que la ruta `/apis` linkee a una _view_ que genere como _output_ el contenido de https://datosgobar.github.io/datosgobar-landing-apis/ (pero en el contexto de la aplicación Pylons)
1. [x] Ajustar la nomenclatura utilizada para los puntos de menú del cabezal de datos.gob.ar para que se ajuste a https://datosgobar.github.io/datosgobar-landing-apis/ (ej: Organizaciones vs Organizaciones con datos)
1. [x] Ajustar el _casing_ de los elementos del punto de menú para que se ajuste a https://datosgobar.github.io/datosgobar-landing-apis/
1. [ ] Ajustar el CSS del cabezal y del footer para que se ajuste a la estética de https://datosgobar.github.io/datosgobar-landing-apis/
