### ISSUE TITLE
Vistas en recursos

### ISSUE THREAD

**Issue by damcasti** [datosgobar/datos.gob.ar#106]
Al querer editar un recurso y seleccionar la solapa vistas en el template de datos.gob.ar, el botón que debería desplegar las vistas disponibles no realiza ninguna acción. Se verifico el .log y no hay ningún evento de error asociado a la acción.

![image](https://user-images.githubusercontent.com/7544958/36977320-7ad2661a-205f-11e8-91e1-2742b1dcae3a.png)

**Comment by iheredia** [comment]
@damcasti el issue está identificado hace rato y está trackeado en los repos de andino:
- https://github.com/datosgobar/portal-andino/issues/78
- https://github.com/datosgobar/portal-andino-theme/issues/80
- https://github.com/datosgobar/portal-andino-theme/issues/103

Creo que @juanehernandez, @abenassi o @poligarcia  te van a dar mas atención sobre esto que yo =p

**Comment by damcasti** [comment]
Genial, no lo había visto :P ... ya lo reviso

**Comment by poligarcia** [comment]
Se cierra al estar cerrados los issues:

* datosgobar/portal-andino#78
* datosgobar/portal-andino-theme#80
* datosgobar/portal-andino-theme#103
