### ISSUE TITLE
Notas de la instalación en Ubuntu 14.04 con solr-tomcat

### ISSUE THREAD

**Issue by mvasquez74** [datosgobar/datos.gob.ar#11]
Para la instalación se siguió con la siguiente documentación:
https://github.com/gobabiertoAR/datos.gob.ar/blob/master/docs/01_instalacion_dev.md

A continuación menciono algunas notas:
1. Se eligió la opción 5.1.B, ya que efectivamente el paquete con Jetty sigue roto.
2. Finalizada la instalación (punto 9) al iniciar el CKAN se observa en la consola el siguiente error:

> 2016-06-15 10:14:13,137 CRITI [ckan.lib.uploader] Please specify a ckan.storage_path in your config for your uploads
> Starting server in PID 1273.
> serving on 0.0.0.0:5000 view at http://127.0.0.1:5000

_Para lo cual configuro el FileStorage, punto 3 de estas notas_
3. Setup de FileStore (Esto se usa para cargar CSVs), con esto se soluciono el punto 2 de estas notas y ya no se muestra ningún error
4. Se continuó con "Otras tareas"
Al crear los datos de pruebas aparece el siguiente error:

> Running setup_app() from ckan.websetup
> 2016-06-15 10:36:42,380 INFO  [ckan.websetup] Creating tables: SUCCESS
> Creating search test data
> /usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
>  sess._flush_warning("related attribute set")
> Creating search test data: Complete!

Al ejecutar el comando para cargar los datos de prueba _**paster create-test-data vocab -c /etc/ckan/default/development.ini**_ se genera el siguiente error:

> Running setup_app() from ckan.websetup
> 2016-06-15 10:55:36,007 INFO  [ckan.websetup] Creating tables: SUCCESS
> Creating vocab test data
> Command vocab not recognized
> Traceback (most recent call last):
>   File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
>     sys.exit(run())
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
>     invoke(command, command_name, options, args[1:])
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
>     exit_code = runner.run(args)
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
>     result = self.command()
>   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1446, in command
>     raise NotImplementedError
> NotImplementedError
1. Se continuó con "Setup de plugins"
   5.1 Set up the DataStore, sin problemas
   5.2 Setup de FileStore (Esto se usa para cargar CSVs), se hizo antes
   5.3 Setup del DataPusher, sin problemas
2. Testeando que todo funciona
   El testeo arrojo la siguiente salida:

> # 
> ## FAIL: ckan.tests.legacy.lib.test_navl.test_formencode_compat
> 
> Traceback (most recent call last):
>   File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/usr/lib/ckan/default/src/ckan/ckan/tests/legacy/lib/test_navl.py", line 334, in test_formencode_compat
>     assert errors == {'email': [u'An email address must contain a single @']}, errors
> AssertionError: {'email': [u'Una direcci\xf3n de correo electr\xf3nico debe contener una sola @ (arroba)']}
> ---
> 
> Ran 1922 tests in 1651.196s
> 
> FAILED (SKIP=12, failures=1)

Verifique si en archivo "test-core.ini" que se usa para el test si habia alguna propiedad que indique el email para el test.

**Comment by pilimayora** [comment]
Hola @mvasquez74 !
Mil disculpas por la demora. Se me traspapeló este issue. 
Ya no es más relevante este tema, pero si estás intentando instalar una versión del portal de datos, te recomiendo que veas nuestro [portal distribuible Andino](https://github.com/datosgobar/portal-andino), que es parte de nuestro [Paquete de Apertura de Datos](https://github.com/datosgobar/paquete-apertura-datos)
Espero que te sirva esta referencia, y cualquier cosa escribinos o creanos otro issue. 
Gracias y disculpas nuevamente!
