### ISSUE TITLE
Revisar estándares de Publicación/Limpieza de Datos

### ISSUE THREAD

**Issue by carohadad** [datosgobar/datos.gob.ar#2]

**Comment by nsampi** [comment]
@meliascosta ahí revise los estándares e hice comentarios. Una vez que los revisemos @chadad hace el merge.

**Comment by pilimayora** [comment]
@meliascosta @nsampi @carohadad en qué estado está esto? Se puede cerrar?

**Comment by nsampi** [comment]
si
