### ISSUE TITLE
Adaptar los formularios de Federar al front de datos.gob.ar

### ISSUE THREAD

**Issue by iheredia** [datosgobar/datos.gob.ar#57]
En la herramienta de federación de los datasets, para que datos gob.ar pueda federar otros hay un bug que no permite ver bien la pantalla, ni hacer scroll para abajo.

![image](https://cloud.githubusercontent.com/assets/1264073/25194357/97681978-2510-11e7-8824-0e0b23c48c8c.png)

**Comment by pilimayora** [comment]
No corresponde.
