### ISSUE TITLE
Problemas de referencias en vista dataset

### ISSUE THREAD

**Issue by aleGpereira** [datosgobar/datos.gob.ar#8]
Buenas, paso a colaborar algo que vi. Estando en esta vista http://www.datos.gob.ar/dataset, pude observar que los iconos en "grupos" cargan mal las referencias cuando hago click en el icono de "economia y finanzas". Una vez hecho eso, si quiero volver a "administracion pública" haciendo click en su ícono en grupos, solamente lo hace si vuelvo a hacer click en el icono de "economia y finanzas". Lo cual carece de todo sentido. Esto fue probado en Chrome y Firefox.

**Comment by iheredia** [comment]
Hola Ale, 

Gracias por hacer notar esto. Lamentablemente no es un bug sino que está pensado para que sea asi; los iconos de grupos funcionan como filtros. Al hacer click en "Economia y Finanzas" se muestran todos los datasets que pertenecen a ese grupo. Como no hay ningun dataset que pertenezca a "Economia y Finanzas" y "Administracion Pública" a la vez, el icono para este segundo grupo queda deshabilitado. 

El filtro de etiquetas funciona de la misma forma. Si seleccionas el tag "Registros", hay muchos tags que desaparecen en las opciones de filtrado. Por ej: "Recursos", ya que no hay ningun dataset que contenga tanto el tag "Registros" como "Recursos". 

De todas formas, estamos evaluando si modificamos la interfaz para que el comportamiento de estos filtros sea mas intuitivo. 

Saludos

**Comment by aleGpereira** [comment]
Ah, ahora entiendo. Probablemente si dijera la palabra "Filtros" sería un poco más facil de intuír. Al leer "grupos" como que intuyo todos los relacionados a ese grupo solamente. Igual queda a la decision de ustedes.

**Comment by carohadad** [comment]
Gracias! Vamos a tener en cuenta la sugerencia para el comportamiento de los filtros.
