### ISSUE TITLE
Habilitar CORS en CKAN?

### ISSUE THREAD

**Issue by jazzido** [datosgobar/datos.gob.ar#9]
Hola,

¿Se podrá habilitar CORS en el CKAN para poder usar los CSVs desde cualquier lado sin tener que bajarlos y copiarlos en otro lado?

Gracias!

**Comment by nsampi** [comment]
Hola @jazzido,

Ahora si los habilitamos, ya deberías poder usar los CSVs. 

Avisanos cualquier cosa!
